### ISSUE TITLE
Force HDR has stopped working. 

### ISSUE THREAD

**Issue by Espnandro** [7gxycn08/ForceAutoHDR#7] opened 2024-04-28 04:58 UTC
It used to work just fine, but for the last few weeks I cannot force HDR on any of the programs I try. Again this used to work for me so it's not me misunderstanding how to find the correct exe or how to adjust the intensity slider, it only recently stopped forcing HDR. I'm wondering if perhaps W11 has broken the functionality with a recent update, or if I altered something that broke it.

**Comment by Espnandro** [comment] 2024-04-28 05:00
Looking further, I realized it is making the necessary registry edit to force HDR in Computer\HKEY_CURRENT_USER\Software\Microsoft\Direct3D 
but it is naming programs incorrectly, I do not know if it has always named the exe files incorrectly or if it just started.

**Comment by 7gxycn08** [comment] 2024-04-28 05:19
What game are you trying to enable AutoHDR for?

**Comment by Espnandro** [comment] 2024-04-28 07:02
Well, first I tried with brothers in arms hell's highway. When I saw it didn't work, I tried enabling it on Firefox as a test. Firefox also didn't work and misspelled in the registry, then I tried to test it again on the league client and once again it didn't work. 
I also know that it used to work on Firefox in the past because it was the exe I was using to test it before, and it did enable.

**Comment by 7gxycn08** [comment] 2024-04-28 07:59
Found the bug and was able to replicate when adding Firefox.
It is caused by inbuilt python function rstrip. 
`exe_name.rstrip('.exe')` 

![Screenshot 2024-04-28 115753](https://github.com/7gxycn08/ForceAutoHDR/assets/121936658/991afae5-e2a8-4ef0-a2a3-e84a2cc4c33f)

It's an easy fix will release a new version soon stay tuned and thanks for reporting it.

**Comment by Espnandro** [comment] 2024-04-28 08:34
![Brothers_in_Arms_-_Hells_Highway_300x351](https://github.com/7gxycn08/ForceAutoHDR/assets/123902154/583dcb20-d8a9-4070-bc3a-ca6392a3aa38)
It's an old game I played when I was younger and recently just played through it again. I do not know if the game was misspelled in the registry or not, but the HDR did not enable for this game. I tried both windowed and full screen to try and fix the issue. Unfortunately, I cannot check the registry value because I already uninstalled the game and cleared it from the registry.

**Comment by 7gxycn08** [comment] 2024-04-28 08:58
Okay no problem.

I just released a fix for the incorrect name entries check it out here [v1.0.0.3](https://github.com/7gxycn08/ForceAutoHDR/releases/tag/v1.0.0.3)

I will close this issue now. Feel free to open a new one if you find a new issue.

**Closed by 7gxycn08** 2024-04-28 08:58 UTC
Labels: bug
